### ISSUE TITLE
API response request

### ISSUE THREAD

**Issue by bigboi314** [pandora-analysis/pypandora#5]
Hello,
I am using your API in order to automate the scan of a new downloaded file, and I am a little bit confused about the POST response
In the POST response, we find a field named 'success': does it mean the success of the request or of the scan ? 
Below you could find an example: 

{**'success': True**, 'taskId': '8be21a02-1a61-4135-acc9-048b89164443', 'seed': 'bLUioDbNvpryi9L08KiKPC94BjFlmHDICPdYJE_9vzg', 'lifetime': 100, 'link': 'https://pandora.circl.lu/analysis/8be21a02-1a61-4135-acc9-048b89164443/seed-bLUioDbNvpryi9L08KiKPC94BjFlmHDICPdYJE_9vzg'}

Have a nice day !

**Comment by Rafiot** [comment]
Hello, it means success of the submission. In order to know how the processing is going, use  `task_status`.

have a nice day!

**Comment by bigboi314** [comment]
Hi, I managed to find what I was looking for, thank you !
